export const CHANGE_TEST = 'CHANGE_TEST';
export const GET_TEST = 'GET_TEST';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';


export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_QUESTIONSBASE = 'SET_QUESTIONSBASE';
export const REQUEST_QUESTIONSBASE = 'REQUEST_QUESTIONSBASE';

export const SET_TASKBASE = 'SET_TASKBASE';
export const REQUEST_TASKBASE = 'REQUEST_TASKBASE';
export const DELETE_TASK = 'DELETE_TASK';

export const GET_DIRECTORY = 'GET_DIRECTORY';
export const DELETE_DIRECTORY = 'DELETE_DIRECTORY';
export const SET_DIRECTORIES = 'SET_DIRECTORIES';
export const ADD_DIRECTORY = 'ADD_DIRECTORY';
export const REQUEST_DIRECTORIES = 'REQUEST_DIRECTORIES';

export const REQUEST_EXAMBASE = 'REQUEST_EXAMBASE';
export const SET_EXAMBASE = 'SET_EXAMBASE';
export const DELETE_EXAM = 'DELETE_EXAM';

export const REQUEST_CLIENTBASE = 'REQUEST_CLIENTBASE';
export const SET_CLIENTBASE = 'SET_CLIENTBASE';

export const REQUEST_USERREQUESTS = 'REQUEST_USERREQUESTS';
export const SET_USERREQUESTS = 'SET_USERREQUESTS';
export const DELETE_USERREQUESTS = 'DELETE_USERREQUESTS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REQUEST_USEREXAMS = 'REQUEST_USEREXAMS';
export const SET_USEREXAMS = 'SET_USEREXAMS';
export const DELETE_USEREXAM = 'DELETE_USEREXAM';
export const REQUEST_USERSUBSCRIPTIONS = 'REQUEST_USERSUBSCRIPTIONS';
export const SET_USERSUBSCRIPTION = 'SET_USERSUBSCRIPTION';
export const UNSUBSCRIPTION_USER = 'UNSUBSCRIPTION_USER';
export const REQUEST_USERINFO = 'REQUEST_USERINFO';
export const SET_USERSTATISTICS = 'SET_USERSTATISTICS';

export const REQUEST_ORGS = 'REQUEST_ORGS';
export const SET_ORGS = 'SET_ORGS';

/*export const GET_EXAM = 'GET_EXAM';*/
export const CHANGE_EXAM = 'CHANGE_EXAM';
export const SET_EXAM = 'SET_EXAM';
export const REQUEST_EXAM = 'REQUEST_EXAM';

export const REQUEST_QUESTION = 'REQUEST_QUESTION';
export const SET_QUESTION = 'SET_QUESTION';

export const REQUEST_TASK = 'REQUEST_TASK';
export const SET_TASK = 'SET_TASK';

export const REQUEST_BASE = 'REQUEST_BASE';
export const SET_BASE = 'SET_BASE';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';

export const REQUEST_ORGCLIENTS = 'REQUEST_ORGCLIENTS';
export const SET_ORGCLIENTS = 'SET_ORGCLIENTS';
export const DELETE_CLIENT = 'DELETE_CLIENT';
/*export const DELETE_DIRECTORY = 'DELETE_DIRECTORY';*/